### ISSUE TITLE
Feature: adding custom formats to rte component

### ISSUE THREAD

**Issue by PMendesWebDev** [umbraco/Umbraco.Headless.Backoffice.Bridge#7]
Hey there!

This is not a bug, it's a feature request :)

Would it be possible to add custom formats to umbh-tinymce helper? 

Example (from the RTE grid component):

`import { LitElement, html } from 'https://cdn.jsdelivr.net/gh/lit/dist@2/all/lit-all.min.js'
import '@headless-backoffice-bridge'

export default class extends LitElement {
  static properties = {
    value: { type: String }
  }

  #toolbar = [
    'ace',
    'styleselect',
    'bold',
    'italic',
    'alignleft',
    'aligncenter',
    'alignright',
    'bullist',
    'numlist',
    'outdent',
    'indent',
    'link',
    'unlink',
    'umbmediapicker'
  ]

  #formats = [{"title":"Headers","items":[{"title":"Header 1 (H1)","block":"h1"},{"title":"H1 Lookalike","selector":"p,span","classes":"h1"},{"title":"Header 2 (H2)","block":"h2"},{"title":"H2 Lookalike","selector":"p,span","classes":"h2"},{"title":"Header 3 (H3)","block":"h3"},{"title":"H3 Lookalike","selector":"p,span","classes":"h3"}]},{"title":"Quotes","items":[{"title":"Style A","block":"blockquote","classes":"quote-a"},{"title":"Style B","block":"blockquote","classes":"quote-b"}]},{"title":"Links","items":[{"title":"CTA Loud","selector":"a","classes":"cta cta-loud"},{"title":"CTA Subtle","selector":"a","classes":"cta cta-subtle"},{"title":"Button look-a-like","selector":"a","classes":"btn btn-mimic"}]},{"title":"Inline colours","items":[{"title":"Orange","inline":"span","classes":"orange"},{"title":"Red","inline":"span","classes":"red"},{"title":"Blue","inline":"span","classes":"blue"}]}]

  createRenderRoot() { return this }

  render() {
    return html`<umbh-tinymce mode="classic" max-image-size="500" .formats=${this.#formats} .toolbar=${this.#toolbar} .value=${this.value} @input=${e => this.value = e.target.value}></umbh-tinymce>`
   }
}`

would render something close to [this](https://our.umbraco.com/documentation/Reference/Configuration-for-Umbraco-7-and-8/tinyMceConfig/#organising-style-formats-into-sub-menus)

![image](https://user-images.githubusercontent.com/34547655/180428645-c58c928a-fe76-44ff-a4d2-09e8b69996c5.png)

**Comment by PMendesWebDev** [comment]
@RyuLindow did you have an opportunity to take an eye on this? :)

**Comment by PMendesWebDev** [comment]
Bumping this

**Comment by sitereactor** [comment]
This is currently not possible with the current RTE in Umbraco unfortunately.
